"""empty message

Revision ID: 0c2d1f680dfa
Revises: d19ba987ed7b
Create Date: 2020-02-19 19:26:53.870582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2d1f680dfa'
down_revision = 'd19ba987ed7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_sku', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_sku')
    # ### end Alembic commands ###
