"""empty message

Revision ID: 30f0feec99b8
Revises: 0c2d1f680dfa
Create Date: 2020-02-19 21:00:44.636933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f0feec99b8'
down_revision = '0c2d1f680dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('user_product_id', sa.Integer(), nullable=True),
    sa.Column('product_rating', sa.Integer(), nullable=True),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
