"""empty message

Revision ID: 4a2103e8312a
Revises: 4003bbed2df5
Create Date: 2020-02-19 19:18:17.780221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2103e8312a'
down_revision = '4003bbed2df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('oid', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
