"""empty message

Revision ID: 9338ce4d0942
Revises: 30f0feec99b8
Create Date: 2020-02-20 09:06:15.124428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9338ce4d0942'
down_revision = '30f0feec99b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_purchase_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_purchase_amount')
    # ### end Alembic commands ###
