"""empty message

Revision ID: 9409adb4e0c4
Revises: 9a258a625f3f
Create Date: 2020-02-18 15:36:35.709831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9409adb4e0c4'
down_revision = '9a258a625f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_email_template', 'footer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_email_template', sa.Column('footer', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
