"""empty message

Revision ID: 9a258a625f3f
Revises: b8491c90b696
Create Date: 2020-02-18 15:27:07.687449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a258a625f3f'
down_revision = 'b8491c90b696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_email_template',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('footer', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_email_template')
    # ### end Alembic commands ###
