"""empty message

Revision ID: c10a886838a5
Revises: bd67c24156db
Create Date: 2020-02-19 18:24:24.597007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10a886838a5'
down_revision = 'bd67c24156db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_product_list', 'user_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_product_list', 'user_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
